### ISSUE TITLE
Add cert and key support for Hisense televisions

### ISSUE THREAD

**Issue by sharpordie** [amirburbea/neeo#5]
Some Hisense televisions (e.g. U7QF) need cert and key files for MQTT connection.

Those files are available here:  
https://github.com/d3nd3/Hisense-mqtt-keyfiles

This is a Python implementation:  
https://github.com/MrAsterisco/hisensetv/commit/3b7d57cc62aeba697c07f610be6319783cad7389

**Comment by amirburbea** [comment]
somehow missed this - will investigate...

**Comment by sharpordie** [comment]
Do you have any news about this?
I have a U7QF from Hisense, I could test it.

**Comment by amirburbea** [comment]
Yes! I finally had time to address in the most recent commit (which now requires .net7/vs2022). Pull the latest version and the hisense library uses those certificates.

I have a HiSense H8G (50H8G to be specific) and verified that adding the certificates did not break anything.
